<?php

use Illuminate\Database\Seeder;

class CThreadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('c_threads')->delete();
        
        \DB::table('c_threads')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Thanks, Curt, for the contribution.',
                'body' => 'Thanks, Curt, for the contribution.',
                'created_at' => '2018-01-08 13:37:42',
                'updated_at' => '2018-01-11 13:37:42',
                'topic_id' => 23,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 328,
                'camp_id' => 1,
                'title' => 'Second Thread',
                'body' => 'Related To some Camp Forums',
                'created_at' => '2018-01-11 13:37:42',
                'updated_at' => '2018-01-11 13:37:42',
                'topic_id' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'jkhsdf',
                'body' => 'jkha jahsdjh asjdh jkhasd jh',
                'created_at' => '2018-01-11 13:37:42',
                'updated_at' => '2018-01-11 13:37:42',
                'topic_id' => 88,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'jkhsdf',
                'body' => 'jkha jahsdjh asjdh jkhasd jh',
                'created_at' => '2018-01-11 13:37:58',
                'updated_at' => '2018-01-11 13:37:58',
                'topic_id' => 88,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Text for Yes Camp',
                'body' => 'Text for Yes Camp',
                'created_at' => '2010-05-10 20:24:34',
                'updated_at' => '2010-05-10 20:24:34',
                'topic_id' => 46,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'camp_id' => 3,
                'title' => 'Supporting yes camp?',
                'body' => 'Supporting yes camp?',
                'created_at' => '2010-05-04 04:22:17',
                'updated_at' => '2010-05-04 04:22:17',
                'topic_id' => 86,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Environmentalism vs Wealth',
                'body' => 'Environmentalism vs Wealth',
                'created_at' => '2009-12-01 19:24:57',
                'updated_at' => '2009-12-01 19:24:57',
                'topic_id' => 105,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'The Bible as Political Document',
                'body' => 'The Bible as Political Document',
                'created_at' => '2012-01-15 04:15:37',
                'updated_at' => '2012-01-15 04:15:37',
                'topic_id' => 61,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 188,
                'camp_id' => 5,
                'title' => 'Hi PeerInfinity, thanks for all the work!',
                'body' => 'Hi PeerInfinity, thanks for all the work!',
                'created_at' => '2010-08-29 23:38:10',
                'updated_at' => '2010-08-29 23:38:10',
                'topic_id' => 94,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Mastophilia of 1 ton+ breasts',
                'body' => 'Mastophilia of 1 ton+ breasts',
                'created_at' => '2012-05-06 21:19:16',
                'updated_at' => '2012-05-06 21:19:16',
                'topic_id' => 63,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Supernatural Healing with Scientific Understanding',
                'body' => 'Supernatural Healing with Scientific Understanding',
                'created_at' => '2010-02-06 08:33:00',
                'updated_at' => '2010-02-06 08:33:00',
                'topic_id' => 92,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 179,
                'camp_id' => 1,
                'title' => 'War occurs in the absence of reason',
                'body' => 'War occurs in the absence of reason',
                'created_at' => '2014-07-24 21:04:22',
                'updated_at' => '2014-07-24 21:04:22',
                'topic_id' => 113,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 75,
                'camp_id' => 9,
                'title' => 'Help make it the right question.',
                'body' => 'Help make it the right question.',
                'created_at' => '2008-07-18 09:01:35',
                'updated_at' => '2008-07-18 09:01:35',
                'topic_id' => 70,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 284,
                'camp_id' => 1,
                'title' => 'Do you include ',
                'body' => 'Do you include ',
                'created_at' => '2012-11-09 21:05:51',
                'updated_at' => '2012-11-09 21:05:51',
                'topic_id' => 140,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 118,
                'camp_id' => 1,
                'title' => 'Model of Multiple Universes: Not an Extension of Physical World',
                'body' => 'Model of Multiple Universes: Not an Extension of Physical World',
                'created_at' => '2009-03-18 08:32:22',
                'updated_at' => '2009-03-18 08:32:22',
                'topic_id' => 99,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Delegated Support',
                'body' => 'Delegated Support',
                'created_at' => '2012-01-15 09:12:20',
                'updated_at' => '2012-01-15 09:12:20',
                'topic_id' => 103,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 83,
                'camp_id' => 10,
                'title' => 'Thanks for contribution...',
                'body' => 'Thanks for contribution...',
                'created_at' => '2010-11-03 07:36:27',
                'updated_at' => '2010-11-03 07:36:27',
                'topic_id' => 16,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 188,
                'camp_id' => 6,
                'title' => 'Is this the right place in the structure for this camp?',
                'body' => 'Is this the right place in the structure for this camp?',
                'created_at' => '2007-12-03 19:00:46',
                'updated_at' => '2007-12-03 19:00:46',
                'topic_id' => 16,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Welcome Ari',
                'body' => 'Welcome Ari',
                'created_at' => '2010-11-02 09:10:36',
                'updated_at' => '2010-11-02 09:10:36',
                'topic_id' => 16,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'How to better organize this topic?',
                'body' => 'How to better organize this topic?',
                'created_at' => '2011-06-28 04:48:08',
                'updated_at' => '2011-06-28 04:48:08',
                'topic_id' => 120,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => '3 great choices.',
                'body' => '3 great choices.',
                'created_at' => '2009-05-23 03:20:18',
                'updated_at' => '2009-05-23 03:20:18',
                'topic_id' => 102,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 283,
                'camp_id' => 1,
                'title' => 'Restructuring this topic?',
                'body' => 'Restructuring this topic?',
                'created_at' => '2013-01-01 21:52:58',
                'updated_at' => '2013-01-01 21:52:58',
                'topic_id' => 141,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'True Desires',
                'body' => 'True Desires',
                'created_at' => '2012-01-15 12:19:12',
                'updated_at' => '2012-01-15 12:19:12',
                'topic_id' => 64,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'This camp should support the YES camp.',
                'body' => 'This camp should support the YES camp.',
                'created_at' => '2012-10-17 07:01:24',
                'updated_at' => '2012-10-17 07:01:24',
                'topic_id' => 42,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'person versus human?',
                'body' => 'person versus human?',
                'created_at' => '2010-02-09 23:03:26',
                'updated_at' => '2010-02-09 23:03:26',
                'topic_id' => 51,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Vitual Reality = Representational Qualia Theory',
                'body' => 'Vitual Reality = Representational Qualia Theory',
                'created_at' => '2012-03-25 03:00:43',
                'updated_at' => '2012-03-25 03:00:43',
                'topic_id' => 71,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 92,
                'camp_id' => 4,
                'title' => 'Change parent of camp to show support of parent camp.',
                'body' => 'Change parent of camp to show support of parent camp.',
                'created_at' => '2009-01-25 04:03:27',
                'updated_at' => '2009-01-25 04:03:27',
                'topic_id' => 43,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Not good enough odds to be considered a rigorous consensus?',
                'body' => 'Not good enough odds to be considered a rigorous consensus?',
                'created_at' => '2009-09-14 00:55:47',
                'updated_at' => '2009-09-14 00:55:47',
                'topic_id' => 104,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Two different topics',
                'body' => 'Two different topics',
                'created_at' => '2007-12-20 23:18:36',
                'updated_at' => '2007-12-20 23:18:36',
                'topic_id' => 22,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'camp_id' => 5,
                'title' => 'How Mormon Exclusivity affects me.',
                'body' => 'How Mormon Exclusivity affects me.',
                'created_at' => '2008-10-20 00:01:17',
                'updated_at' => '2008-10-20 00:01:17',
                'topic_id' => 22,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'camp_id' => 41,
                'title' => 'Ask questions',
                'body' => 'Ask questions',
                'created_at' => '2010-05-06 19:19:26',
                'updated_at' => '2010-05-06 19:19:26',
                'topic_id' => 88,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'camp_id' => 20,
                'title' => 'Of free will and neural infrastructure',
                'body' => 'Of free will and neural infrastructure',
                'created_at' => '2012-07-12 21:29:29',
                'updated_at' => '2012-07-12 21:29:29',
                'topic_id' => 88,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'camp_id' => 37,
                'title' => 'Some thoughts on this camp\'s statement',
                'body' => 'Some thoughts on this camp\'s statement',
                'created_at' => '2010-05-31 19:48:49',
                'updated_at' => '2010-05-31 19:48:49',
                'topic_id' => 88,
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 85,
                'camp_id' => 13,
                'title' => 'UMSITW is the most succinct explanation of C available!',
                'body' => 'UMSITW is the most succinct explanation of C available!',
                'created_at' => '2010-05-17 19:53:21',
                'updated_at' => '2010-05-17 19:53:21',
                'topic_id' => 88,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'camp_id' => 23,
                'title' => 'Welcome to the not supernatural camp.',
                'body' => 'Welcome to the not supernatural camp.',
                'created_at' => '2009-08-12 09:41:07',
                'updated_at' => '2009-08-12 09:41:07',
                'topic_id' => 88,
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 243,
                'camp_id' => 7,
                'title' => 'New Name: ',
                'body' => 'New Name: ',
                'created_at' => '2009-07-06 19:54:49',
                'updated_at' => '2009-07-06 19:54:49',
                'topic_id' => 88,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'camp_id' => 14,
                'title' => 'Reified higher dimensions are over-kill',
                'body' => 'Reified higher dimensions are over-kill',
                'created_at' => '2009-08-06 07:32:23',
                'updated_at' => '2009-08-06 07:32:23',
                'topic_id' => 88,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 271,
                'camp_id' => 54,
                'title' => 'Checking out your work.',
                'body' => 'Checking out your work.',
                'created_at' => '2012-07-20 08:42:33',
                'updated_at' => '2012-07-20 08:42:33',
                'topic_id' => 88,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'camp_id' => 25,
                'title' => 'The Trail of Breadcrumbs',
                'body' => 'The Trail of Breadcrumbs',
                'created_at' => '2012-11-24 23:05:34',
                'updated_at' => '2012-11-24 23:05:34',
                'topic_id' => 88,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 309,
                'camp_id' => 58,
                'title' => 'Chalmers\' error',
                'body' => 'Chalmers\' error',
                'created_at' => '2013-10-06 23:19:01',
                'updated_at' => '2013-10-06 23:19:01',
                'topic_id' => 88,
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 261,
                'camp_id' => 50,
                'title' => 'RQT Thread Sidebar',
                'body' => 'RQT Thread Sidebar',
                'created_at' => '2012-06-06 22:14:57',
                'updated_at' => '2012-06-06 22:14:57',
                'topic_id' => 88,
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'camp_id' => 29,
                'title' => 'The ',
                'body' => 'The ',
                'created_at' => '2010-03-09 01:35:56',
                'updated_at' => '2010-03-09 01:35:56',
                'topic_id' => 88,
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 35,
                'camp_id' => 53,
                'title' => 'Helping to build more consensus.',
                'body' => 'Helping to build more consensus.',
                'created_at' => '2012-06-24 23:00:48',
                'updated_at' => '2012-06-24 23:00:48',
                'topic_id' => 88,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 116,
                'camp_id' => 6,
                'title' => 'Classic Qualia Possibility Proof?',
                'body' => 'Classic Qualia Possibility Proof?',
                'created_at' => '2009-01-26 05:02:10',
                'updated_at' => '2009-01-26 05:02:10',
                'topic_id' => 88,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 38,
                'camp_id' => 4,
                'title' => 'Updates of image links?',
                'body' => 'Updates of image links?',
                'created_at' => '2009-02-06 11:09:24',
                'updated_at' => '2009-02-06 11:09:24',
                'topic_id' => 88,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'camp_id' => 2,
                'title' => 'Definition of consciousness?',
                'body' => 'Definition of consciousness?',
                'created_at' => '2009-05-28 07:23:51',
                'updated_at' => '2009-05-28 07:23:51',
                'topic_id' => 88,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 35,
                'camp_id' => 15,
                'title' => 'a quibble with substance',
                'body' => 'a quibble with substance',
                'created_at' => '2010-06-07 11:10:03',
                'updated_at' => '2010-06-07 11:10:03',
                'topic_id' => 88,
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 96,
                'camp_id' => 1,
                'title' => 'TSC 2014 in Tucson',
                'body' => 'TSC 2014 in Tucson',
                'created_at' => '2008-12-29 21:50:00',
                'updated_at' => '2008-12-29 21:50:00',
                'topic_id' => 88,
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'camp_id' => 19,
                'title' => 'Is property dualism Cartesian dualism?',
                'body' => 'Is property dualism Cartesian dualism?',
                'created_at' => '2012-06-16 18:50:17',
                'updated_at' => '2012-06-16 18:50:17',
                'topic_id' => 88,
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 131,
                'camp_id' => 39,
                'title' => 'Language & the recursive/self-reflective nature of consciousness',
                'body' => 'Language & the recursive/self-reflective nature of consciousness',
                'created_at' => '2010-05-29 13:01:01',
                'updated_at' => '2010-05-29 13:01:01',
                'topic_id' => 88,
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 1,
                'camp_id' => 3,
                'title' => 'Propose moving this \'pan psychic\' camp.',
                'body' => 'Propose moving this \'pan psychic\' camp.',
                'created_at' => '2011-10-03 03:06:23',
                'updated_at' => '2011-10-03 03:06:23',
                'topic_id' => 88,
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 131,
                'camp_id' => 31,
                'title' => 'Can you link me to some resource supporting this theory?',
                'body' => 'Can you link me to some resource supporting this theory?',
                'created_at' => '2011-09-19 16:18:19',
                'updated_at' => '2011-09-19 16:18:19',
                'topic_id' => 88,
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 1,
                'camp_id' => 8,
                'title' => 'This can\'t be a corelary can it?',
                'body' => 'This can\'t be a corelary can it?',
                'created_at' => '2009-01-26 09:50:32',
                'updated_at' => '2009-01-26 09:50:32',
                'topic_id' => 88,
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 1,
                'camp_id' => 34,
                'title' => 'How is this Panexperientialism different than rep qualia?',
                'body' => 'How is this Panexperientialism different than rep qualia?',
                'created_at' => '2011-04-19 08:53:26',
                'updated_at' => '2011-04-19 08:53:26',
                'topic_id' => 88,
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 159,
                'camp_id' => 33,
                'title' => 'Moving the ELN camp?',
                'body' => 'Moving the ELN camp?',
                'created_at' => '2009-11-15 22:50:17',
                'updated_at' => '2009-11-15 22:50:17',
                'topic_id' => 88,
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'conciliance vs canon',
                'body' => 'conciliance vs canon',
                'created_at' => '2007-11-28 21:46:03',
                'updated_at' => '2007-11-28 21:46:03',
                'topic_id' => 24,
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'What rainbow? - I don\'t see any rainbow!',
                'body' => 'What rainbow? - I don\'t see any rainbow!',
                'created_at' => '2008-10-08 20:26:43',
                'updated_at' => '2008-10-08 20:26:43',
                'topic_id' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 1,
                'camp_id' => 10,
                'title' => 'Can we get a camp representing these important ideas started?',
                'body' => 'Can we get a camp representing these important ideas started?',
                'created_at' => '2011-07-08 09:06:26',
                'updated_at' => '2011-07-08 09:06:26',
                'topic_id' => 85,
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Expanding this survey topic.',
                'body' => 'Expanding this survey topic.',
                'created_at' => '2009-03-11 14:06:36',
                'updated_at' => '2009-03-11 14:06:36',
                'topic_id' => 97,
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Welcome to the Wiki Leaks survey topic',
                'body' => 'Welcome to the Wiki Leaks survey topic',
                'created_at' => '2010-12-06 05:15:34',
                'updated_at' => '2010-12-06 05:15:34',
                'topic_id' => 119,
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 108,
                'camp_id' => 10,
                'title' => 'More Info Needed.',
                'body' => 'More Info Needed.',
                'created_at' => '2009-04-11 23:06:39',
                'updated_at' => '2009-04-11 23:06:39',
                'topic_id' => 53,
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 35,
                'camp_id' => 2,
                'title' => 'Good improvements...',
                'body' => 'Good improvements...',
                'created_at' => '2010-02-28 00:13:36',
                'updated_at' => '2010-02-28 00:13:36',
                'topic_id' => 83,
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Thanks for contributuion.',
                'body' => 'Thanks for contributuion.',
                'created_at' => '2008-11-15 22:31:30',
                'updated_at' => '2008-11-15 22:31:30',
                'topic_id' => 83,
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Illusion Doctrin belongs in compatible camp.',
                'body' => 'Illusion Doctrin belongs in compatible camp.',
                'created_at' => '2012-01-15 03:39:05',
                'updated_at' => '2012-01-15 03:39:05',
                'topic_id' => 128,
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Welcom Dystopian Welcher!',
                'body' => 'Welcom Dystopian Welcher!',
                'created_at' => '2011-05-07 09:17:11',
                'updated_at' => '2011-05-07 09:17:11',
                'topic_id' => 121,
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 30,
                'camp_id' => 1,
                'title' => 'from thread',
                'body' => 'from thread',
                'created_at' => '2007-11-08 06:33:54',
                'updated_at' => '2007-11-08 06:33:54',
                'topic_id' => 30,
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 1,
                'camp_id' => 2,
                'title' => 'Theist-Friendly Atheism',
                'body' => 'Theist-Friendly Atheism',
                'created_at' => '2012-11-27 18:11:45',
                'updated_at' => '2012-11-27 18:11:45',
                'topic_id' => 54,
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 1,
                'camp_id' => 4,
                'title' => 'Christian Transhumanist',
                'body' => 'Christian Transhumanist',
                'created_at' => '2008-08-23 21:43:25',
                'updated_at' => '2008-08-23 21:43:25',
                'topic_id' => 54,
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 1,
                'camp_id' => 2,
                'title' => 'Google doc draft for this camp.',
                'body' => 'Google doc draft for this camp.',
                'created_at' => '2013-06-24 04:05:46',
                'updated_at' => '2013-06-24 04:05:46',
                'topic_id' => 154,
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'new ',
                'body' => 'new ',
                'created_at' => '2013-07-12 03:50:56',
                'updated_at' => '2013-07-12 03:50:56',
                'topic_id' => 154,
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 35,
                'camp_id' => 10,
                'title' => 'What is a Computer?',
                'body' => 'What is a Computer?',
                'created_at' => '2012-11-27 17:37:39',
                'updated_at' => '2012-11-27 17:37:39',
                'topic_id' => 23,
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 1,
                'camp_id' => 15,
                'title' => 'Abandonmenet of Functional Property Dualism?',
                'body' => 'Abandonmenet of Functional Property Dualism?',
                'created_at' => '2010-05-13 20:07:37',
                'updated_at' => '2010-05-13 20:07:37',
                'topic_id' => 23,
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Unapproachable via science',
                'body' => 'Unapproachable via science',
                'created_at' => '2007-09-30 02:52:27',
                'updated_at' => '2007-09-30 02:52:27',
                'topic_id' => 23,
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 1,
                'camp_id' => 7,
                'title' => 'Removeing \'Brain Linked\'?',
                'body' => 'Removeing \'Brain Linked\'?',
                'created_at' => '2008-10-22 02:28:37',
                'updated_at' => '2008-10-22 02:28:37',
                'topic_id' => 23,
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 38,
                'camp_id' => 13,
                'title' => 'Hello JohnDe1941,',
                'body' => 'Hello JohnDe1941,',
                'created_at' => '2008-02-01 10:08:36',
                'updated_at' => '2008-02-01 10:08:36',
                'topic_id' => 23,
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 1,
                'camp_id' => 11,
                'title' => 'Same camp as ',
                'body' => 'Same camp as ',
                'created_at' => '2007-10-26 05:26:44',
                'updated_at' => '2007-10-26 05:26:44',
                'topic_id' => 23,
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 1,
                'camp_id' => 9,
                'title' => 'Transition to new consciousness theories topic?',
                'body' => 'Transition to new consciousness theories topic?',
                'created_at' => '2007-11-18 10:21:41',
                'updated_at' => '2007-11-18 10:21:41',
                'topic_id' => 23,
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 1,
                'camp_id' => 8,
                'title' => 'I believe Chalmers will not agree with this camp',
                'body' => 'I believe Chalmers will not agree with this camp',
                'created_at' => '2007-10-20 21:13:37',
                'updated_at' => '2007-10-20 21:13:37',
                'topic_id' => 23,
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 85,
                'camp_id' => 21,
                'title' => 'New Theories Topic.',
                'body' => 'New Theories Topic.',
                'created_at' => '2009-01-08 08:06:18',
                'updated_at' => '2009-01-08 08:06:18',
                'topic_id' => 23,
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => '4-way muddle',
                'body' => '4-way muddle',
                'created_at' => '2010-01-05 23:08:26',
                'updated_at' => '2010-01-05 23:08:26',
                'topic_id' => 106,
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'The meaning of equity',
                'body' => 'The meaning of equity',
                'created_at' => '2008-11-03 19:09:25',
                'updated_at' => '2008-11-03 19:09:25',
                'topic_id' => 7,
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 283,
                'camp_id' => 1,
                'title' => 'Interesting...',
                'body' => 'Interesting...',
                'created_at' => '2012-11-30 22:38:16',
                'updated_at' => '2012-11-30 22:38:16',
                'topic_id' => 144,
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 180,
                'camp_id' => 26,
                'title' => 'Welcome Les',
                'body' => 'Welcome Les',
                'created_at' => '2010-05-07 07:05:40',
                'updated_at' => '2010-05-07 07:05:40',
                'topic_id' => 81,
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 1,
                'camp_id' => 25,
                'title' => 'Great start to a great camp.',
                'body' => 'Great start to a great camp.',
                'created_at' => '2010-03-14 01:51:53',
                'updated_at' => '2010-03-14 01:51:53',
                'topic_id' => 81,
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 1,
                'camp_id' => 13,
            'title' => 'Canonizing Penrose-Hameroff (Orch OR)',
            'body' => 'Canonizing Penrose-Hameroff (Orch OR)',
                'created_at' => '2010-05-24 06:55:41',
                'updated_at' => '2010-05-24 06:55:41',
                'topic_id' => 81,
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 1,
                'camp_id' => 4,
                'title' => 'resonance patterns',
                'body' => 'resonance patterns',
                'created_at' => '2008-11-05 00:39:21',
                'updated_at' => '2008-11-05 00:39:21',
                'topic_id' => 81,
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 1,
                'camp_id' => 21,
                'title' => 'Cleaning up and making camps consistant.',
                'body' => 'Cleaning up and making camps consistant.',
                'created_at' => '2009-02-28 23:24:12',
                'updated_at' => '2009-02-28 23:24:12',
                'topic_id' => 81,
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Change \'Mind\' Experts to Consciousness Experts',
                'body' => 'Change \'Mind\' Experts to Consciousness Experts',
                'created_at' => '2008-11-14 00:14:02',
                'updated_at' => '2008-11-14 00:14:02',
                'topic_id' => 81,
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Heat Pollution',
                'body' => 'Heat Pollution',
                'created_at' => '2012-01-16 08:35:26',
                'updated_at' => '2012-01-16 08:35:26',
                'topic_id' => 66,
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 114,
                'camp_id' => 1,
                'title' => 'Can\'t support agreement statement',
                'body' => 'Can\'t support agreement statement',
                'created_at' => '2012-11-16 20:12:53',
                'updated_at' => '2012-11-16 20:12:53',
                'topic_id' => 133,
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'why doesn\'t italic work?',
                'body' => 'why doesn\'t italic work?',
                'created_at' => '2008-11-03 17:22:47',
                'updated_at' => '2008-11-03 17:22:47',
                'topic_id' => 73,
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'A New Option Submitted, Please Adjust your Support',
                'body' => 'A New Option Submitted, Please Adjust your Support',
                'created_at' => '2012-03-22 22:43:57',
                'updated_at' => '2012-03-22 22:43:57',
                'topic_id' => 69,
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Lord Yo, thanks for contributions.',
                'body' => 'Lord Yo, thanks for contributions.',
                'created_at' => '2008-01-24 09:07:39',
                'updated_at' => '2008-01-24 09:07:39',
                'topic_id' => 49,
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 85,
                'camp_id' => 1,
                'title' => 'Great topic.',
                'body' => 'Great topic.',
                'created_at' => '2010-05-15 20:30:50',
                'updated_at' => '2010-05-15 20:30:50',
                'topic_id' => 114,
            ),
            94 => 
            array (
                'id' => 95,
                'user_id' => 35,
                'camp_id' => 2,
                'title' => 'Welcome to this camp Xodarap',
                'body' => 'Welcome to this camp Xodarap',
                'created_at' => '2008-09-25 07:27:25',
                'updated_at' => '2008-09-25 07:27:25',
                'topic_id' => 2,
            ),
            95 => 
            array (
                'id' => 96,
                'user_id' => 35,
                'camp_id' => 4,
                'title' => 'I\'m not sure what the word ',
                'body' => 'I\'m not sure what the word ',
                'created_at' => '2008-09-24 21:04:56',
                'updated_at' => '2008-09-24 21:04:56',
                'topic_id' => 2,
            ),
            96 => 
            array (
                'id' => 97,
                'user_id' => 1,
                'camp_id' => 20,
                'title' => 'Gaia is not God',
                'body' => 'Gaia is not God',
                'created_at' => '2010-03-31 19:16:43',
                'updated_at' => '2010-03-31 19:16:43',
                'topic_id' => 2,
            ),
            97 => 
            array (
                'id' => 98,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Camp ',
                'body' => 'Camp ',
                'created_at' => '2010-02-03 11:19:32',
                'updated_at' => '2010-02-03 11:19:32',
                'topic_id' => 2,
            ),
            98 => 
            array (
                'id' => 99,
                'user_id' => 1,
                'camp_id' => 18,
                'title' => 'The broader conclusion is unwarranted',
                'body' => 'The broader conclusion is unwarranted',
                'created_at' => '2009-07-20 10:17:46',
                'updated_at' => '2009-07-20 10:17:46',
                'topic_id' => 2,
            ),
            99 => 
            array (
                'id' => 100,
                'user_id' => 1,
                'camp_id' => 1,
                'title' => 'Let\'s unify the yes camps.',
                'body' => 'Let\'s unify the yes camps.',
                'created_at' => '2009-10-26 03:20:44',
                'updated_at' => '2009-10-26 03:20:44',
                'topic_id' => 91,
            ),
            100 => 
            array (
                'id' => 101,
                'user_id' => 1,
                'camp_id' => 2,
                'title' => 'The most important endeavour?',
                'body' => 'The most important endeavour?',
                'created_at' => '2010-04-06 20:06:03',
                'updated_at' => '2010-04-06 20:06:03',
                'topic_id' => 91,
            ),
            101 => 
            array (
                'id' => 102,
                'user_id' => 1,
                'camp_id' => 3,
                'title' => 'Is this a yes or no camp?',
                'body' => 'Is this a yes or no camp?',
                'created_at' => '2009-02-05 20:21:34',
                'updated_at' => '2009-02-05 20:21:34',
                'topic_id' => 91,
            ),
            102 => 
            array (
                'id' => 103,
                'user_id' => 30,
                'camp_id' => 2,
                'title' => 'This is a test.',
                'body' => 'This is a test.',
                'created_at' => '2007-12-16 23:29:01',
                'updated_at' => '2007-12-16 23:29:01',
                'topic_id' => 29,
            ),
            103 => 
            array (
                'id' => 104,
                'user_id' => 1,
                'camp_id' => 6,
                'title' => 'Test some posting.',
                'body' => 'Test some posting.',
                'created_at' => '2008-12-16 07:58:10',
                'updated_at' => '2008-12-16 07:58:10',
                'topic_id' => 29,
            ),
            104 => 
            array (
                'id' => 105,
                'user_id' => 1,
                'camp_id' => 3,
                'title' => 'Testing, 2 3 4.',
                'body' => 'Testing, 2 3 4.',
                'created_at' => '2013-07-08 07:50:15',
                'updated_at' => '2013-07-08 07:50:15',
                'topic_id' => 29,
            ),
            105 => 
            array (
                'id' => 106,
                'user_id' => 30,
                'camp_id' => 1,
                'title' => 'bold italic test.',
                'body' => 'bold italic test.',
                'created_at' => '2008-11-30 04:30:38',
                'updated_at' => '2008-11-30 04:30:38',
                'topic_id' => 29,
            ),
            106 => 
            array (
                'id' => 107,
                'user_id' => 172,
                'camp_id' => 1,
                'title' => 'Great topic.',
                'body' => 'Great topic.',
                'created_at' => '2010-02-05 08:35:13',
                'updated_at' => '2010-02-05 08:35:13',
                'topic_id' => 112,
            ),
            107 => 
            array (
                'id' => 108,
                'user_id' => 90,
                'camp_id' => 1,
                'title' => 'Qualia exist - here\'s how',
                'body' => 'Qualia exist - here\'s how',
                'created_at' => '2008-12-28 11:31:52',
                'updated_at' => '2008-12-28 11:31:52',
                'topic_id' => 82,
            ),
            108 => 
            array (
                'id' => 109,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'kjsdfkj',
                'body' => 'jhsadjfhjksdf',
                'created_at' => '2018-01-18 09:36:01',
                'updated_at' => '2018-01-18 09:36:01',
                'topic_id' => 24,
            ),
            109 => 
            array (
                'id' => 110,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'New Thread For 24-Transhuman',
                'body' => 'New Thread For 24-Transhuman',
                'created_at' => '2018-01-18 09:41:10',
                'updated_at' => '2018-01-18 09:41:10',
                'topic_id' => 24,
            ),
            110 => 
            array (
                'id' => 111,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'New Thread For 24-Transhuman',
                'body' => 'New Thread For 24-Transhuman',
                'created_at' => '2018-01-18 09:42:30',
                'updated_at' => '2018-01-18 09:42:30',
                'topic_id' => 24,
            ),
            111 => 
            array (
                'id' => 112,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'Another thread For 24',
                'body' => 'Another thread For 24',
                'created_at' => '2018-01-18 09:47:43',
                'updated_at' => '2018-01-18 09:47:43',
                'topic_id' => 24,
            ),
            112 => 
            array (
                'id' => 113,
                'user_id' => 0,
                'camp_id' => 1,
                'title' => 'Directly from thread',
                'body' => 'Firectly from thread',
                'created_at' => '2018-01-18 09:56:56',
                'updated_at' => '2018-01-18 09:56:56',
                'topic_id' => 23,
            ),
        ));
        
        
    }
}