def test_cases(index):
    return testCases[index]


critical = "Critical"
major = "Major"
moderate = "Moderate"
low = "Low"

testCases = {

    0: [critical, 'When user goes to Canonizer main page, page should be loaded Properly'],
    1: [critical, 'In Home page, when user click "Register" button, User should see User Registration Page'],
    2: [critical, 'In Home page, when user click "Login" button,  User should see Login Page'],
    3: [critical, 'In Login Page, when user login with a valid user, he should see Home Page'],
    4: [critical, 'In Login Page, when user login with a in-valid user, user must see Error Message'],
    5: [moderate, 'In User Registration Page, When user doesn\'t put First Name, user must see Error Message'],
    6: [moderate, 'In User Registration Page, When user doesn\'t put Last Name, user must see Error Message'],
    7: [moderate, 'In User Registration Page, When user doesn\'t put Email, user must see Error Message'],
    8: [moderate, 'In User Registration Page, When user puts blank password, user must see Error Message'],
    9: [moderate, 'In User Registration Page, when user puts invalid password,user must see Error Message'],
    10: [moderate, 'In User Registration Page, when user puts different password for confirmation,user must see Error Message'],
    11: [critical, 'When user clicks on What is Canonizer.com, page should be loaded.'],
    12: [critical, 'If any unauthenticated user wants to join the camp, User should be directed to the login page'],
    13: [low, 'When the main page loads, Text on button to upload all topic is "Load All Topics"'],
    14: [low, 'Register page should have "Login" option/button for existing users'],
    15: [low, 'Login Page should have "Register" Option/button for new users'],
    16: [low, 'On Registration Page, All Mandatory Fields are marked with * Sign'],
    17: [critical, 'In forgot password page, When user click on "Forgot Password" link ,User should see forgot password page'],
    18: [critical, 'In forgot password page, When user doesn\'t put Email, user must see error message.'],
    19: [critical, 'In forgot password page, When user put Email which is not in database, user must see error message'],
    20: [critical, 'In forgot password page, When user put valid Email,User should receive reset link '],
    21: [critical, 'On forgot password Page, All Mandatory Fields are marked with * Sign'],
    22: [critical, 'In Browse page, When user click on "Browse" ,user should see browse page'],
    23: [critical, 'In Browse page, When user click on "Only My Topics", user should see only topics created by own'],
    24: [critical, 'In Upload File page, When user click on "Upload File",user should see upload file page'],
    25: [critical, 'In Upload File page, When user doesn\'t put File name,user should see error message'],
    26: [critical, 'In Create New Topic page, When user click on "Create New Topic", user should see Create New Topic page'],
    27: [critical, 'In Create New Topic page, When user doesn\'t put Nick name,user should see error message'],
    28: [critical, 'In Create New Topic page, When user doesn\'t put Topic name,user should see error message'],
    29: [critical, 'In Create New Topic page, When user put blank spaces in topic name,user should see error message'],
    30: [low, 'On Create New Topic Page, All Mandatory Fields are marked with * Sign'],
    31: [moderate, 'In Create New Topic page, When user enter duplicate Nick name,user should see error message'],
    32: [low, 'When user goes click on Create New Topic without logging in, Login Page page should be loaded'],
    33: [critical, 'In log out page, user should see home page'],
    34: [critical, 'In Account Settings page, When user click on "Account Settings" ,user should see Account Settings page'],
    35: [critical, 'In Account Settings page, When user click on "Manage Profile Info" subtab,user should see Profile page'],
    36: [critical, 'In Account Settings page, When user click on "Add & Manage Nick Names" subtab,user should see Nick Names page'],
    37: [critical, 'In Account Settings page, When user click on "My Supports" subtab,user should see Supported Camps page'],
    38: [critical, 'In Account Settings page, When user click on "Default Algorithm" subtab,user should see Default Algorithm page'],
    39: [critical, 'In Account Settings page, When user click on "Change Password" subtab,user should see Change Password page'],
    40: [moderate, 'On Change Password Page, All Mandatory Fields are marked with * Sign'],
    41: [moderate, 'On Change Password Page, When user doesn\'t put Current Password name,user should see error message'],
    42: [moderate, 'On Change Password Page, When user doesn\'t put New Password name,user should see error message'],
    43: [moderate, 'On Change Password Page, When user doesn\'t put Confirm Password name,user should see error message'],
    44: [moderate, 'On Change Password Page, When user puts invalid current password, user must see Error Message '],
    45: [moderate, 'On Change Password Page, When user puts mismatch password, user must see Error Message'],
    46: [moderate, 'On Change Password Page, When new password is same as current, user must see Error Message'],
    47: [critical, 'When user goes click on Help without logging in, Help page should be loaded Properly'],
    48: [critical, 'When user goes click on Help with login, Help page should be loaded Properly'],
    49: [critical, 'When user click on Steps to Create a New Topic with login, page should be loaded Properly'],
    50: [critical, 'When user click on Dealing With Disagreements with login, page should be loaded Properly'],
    51: [critical, 'When user click on Wiki Markup Information with login, page should be loaded Properly'],
    52: [critical, 'When user click on Adding the Canonizer Feedback Camp Outline to Internet Articles with login, page should be loaded Properly'],
    53: [critical, 'When user click on Steps to Create a New Topic without login, page should be loaded Properly'],
    54: [critical, 'When user click on Dealing With Disagreements without login, page should be loaded Properly'],
    55: [critical, 'When user click on Wiki Markup Information without login, page should be loaded Properly'],
    56: [critical, 'When user click on Adding the Canonizer Feedback Camp Outline to Internet Articles without login, page should be loaded Properly'],
    57: [critical, 'On Nick Names Page, All Mandatory Fields are marked with * Sign'],
    58: [critical, 'On Nick Names Page, When user doesn\'t put Nick Name , user must see Error Message'],
    59: [critical, 'On Nick Names Page, When user put duplicate Nick Name , user must see Error Message'],
    60: [critical, 'On Nick Names Page, When user put blank spaces in Nick Name, user must see Error Message'],
    61: [critical, 'On Nick Names Page, When user put valid Nick Name,User should see success message'],
    62: [critical, 'On Manage Profile Info Page, All Mandatory Fields are marked with * Sign'],
    63: [critical, 'On Manage Profile Info Page, When user doesn\'t put First Name , user must see Error Message'],
    64: [critical, 'On Manage Profile Info Page, When user doesn\'t put Last Name , user must see Error Message'],
    65: [critical, 'On Browse Page,When user select /general/ namespace from drop down, User must see topics under /general/ namespace'],
    66: [critical, 'On Browse Page,When user select /corporations/ namespace from drop down, User must see topics under /corporations/ namespace'],
    67: [critical, 'On Browse Page,When user select /crypto_currency/ namespace from drop down, User must see topics under /crypto_currency/ namespace'],
    68: [critical, 'On Browse Page,When user select /family/ namespace from drop down, User must see topics under /family/ namespace'],
    69: [critical, 'On Browse Page,When user select /family/Jesperson_Oscar_F/ namespace from drop down, User must see topics under /family/Jesperson_Oscar_F/ namespace'],
    70: [critical, 'On Browse Page,When user select /Occupy Wall Street/ namespace from drop down, User must see topics under /Occupy Wall Street/ namespace'],
    71: [critical, 'On Browse Page,When user select /organizations/ namespace from drop down, User must see topics under /organizations/ namespace'],
    72: [critical, 'On Browse Page,When user select /organizations/canonizer/ namespace from drop down, User must see topics under /organizations/canonizer/ namespace'],
    73: [critical, 'On Browse Page,When user select /organizations/canonizer/help/ namespace from drop down, User must see topics under /organizations/canonizer/help/ namespace'],
    74: [critical, 'On Browse Page,When user select /organizations/mta/ namespace from drop down, User must see topics under /organizations/mta/ namespace'],
    75: [critical, 'On Browse Page,When user select /organizations/TV07/ namespace from drop down, User must see topics under /organizations/TV07/ namespace'],
    76: [critical, 'On Browse Page,When user select /organizations/wta/ namespace from drop down, User must see topics under /organizations/wta/ namespace'],
    77: [critical, 'On Browse Page,When user select /personal_attributes/ namespace from drop down, User must see topics under /personal_attributes/ namespace'],
    78: [critical, 'On Browse Page,When user select /personal_reputations/ namespace from drop down, User must see topics under /personal_reputations/ namespace'],
    79: [critical, 'On Browse Page,When user select /professional_services/ namespace from drop down, User must see topics under /professional_services/ namespace'],
    80: [critical, 'On Browse Page,When user select /sandbox/ namespace from drop down, User must see topics under /sandbox/ namespace'],
    81: [critical, 'On Browse Page,When user select /terminology/ namespace from drop down, User must see topics under /terminology/ namespace'],
    82: [critical, 'On Browse Page,When user select /www/ namespace from drop down, User must see topics under /www/ namespace'],
    83: [critical, 'On Browse Page,When user select All namespace from drop down, User must see topics under All namespace'],
    84: [critical, 'On Browse Page,When user click on Browse, User must see topics under All namespace'],
    85: [critical, 'On Browse Page,When user select /general/ namespace and Only My Topics, User must see own topics under /general/ namespace'],
    86: [critical, 'On Browse Page,When user select /corporations/ namespace and Only My Topics, User must see own topics under /corporations/ namespace'],
    87: [critical, 'On Browse Page,When user select /crypto_currency/ namespace and Only My Topics, User must see own topics under /crypto_currency/ namespace'],
    88: [critical, 'On Browse Page,When user select /family/ namespace and Only My Topics, User must see own topics under /family/ namespace'],
    89: [critical, 'On Browse Page,When user select /family/Jesperson_Oscar_F/ namespace and Only My Topics, User must see own topics under /family/Jesperson_Oscar_F/ namespace'],
    90: [critical, 'On Browse Page,When user select /Occupy Wall Street/ namespace and Only My Topics, User must see own topics under /Occupy Wall Street/ namespace'],
    91: [critical, 'On Browse Page,When user select /organizations/ namespace and Only My Topics, User must see own topics under /organizations/ namespace'],
    92: [critical, 'On Browse Page,When user select /organizations/canonizer/ namespace and Only My Topics, User must see own topics under /organizations/canonizer/ namespace'],
    93: [critical, 'On Browse Page,When user select /organizations/canonizer/help/ namespace and Only My Topics, User must see own topics under /organizations/canonizer/help/ namespace'],
    94: [critical, 'On Browse Page,When user select /organizations/mta/ namespace and Only My Topics, User must see own topics under /organizations/mta/ namespace'],
    95: [critical, 'On Browse Page,When user select /organizations/TV07/ namespace and Only My Topics, User must see own topics under /organizations/TV07/ namespace'],
    96: [critical, 'On Browse Page,When user select /organizations/wta/ namespace and Only My Topics, User must see own topics under /organizations/wta/ namespace'],
    97: [critical, 'On Browse Page,When user select /personal_attributes/ namespace and Only My Topics, User must see own topics under /personal_attributes/ namespace'],
    98: [critical, 'On Browse Page,When user select /personal_reputations/ namespace and Only My Topics, User must see own topics under /personal_reputations/ namespace'],
    99: [critical, 'On Browse Page,When user select /professional_services/ namespace and Only My Topics, User must see own topics under /professional_services/ namespace'],
    100: [critical, 'On Browse Page,When user select /sandbox/ namespace and Only My Topics, User must see own topics under /sandbox/ namespace'],
    101: [critical, 'On Browse Page,When user select /terminology/ namespace and Only My Topics, User must see own topics under /terminology/ namespace'],
    102: [critical, 'On Browse Page,When user select /www/ namespace and Only My Topics, User must see own topics under /www/ namespace'],
    103: [critical, 'On Browse Page,When user select All namespace and Only My Topics, User must see own topics under All namespace'],
    104: [critical, 'When user logged in and clicks on White Paper, User should see white paper in new window'],
    105: [critical, 'When user without logged in clicks on White Paper, User should see white paper in new window'],
    106: [critical, 'When user logged in and clicks on Blog Page, User should see blog page '],
    107: [critical, 'When user without logged in clicks on Blog Page, User should see blog page '],
    108: [critical, 'When user click on Algorithm Information link,user should see all canonizer algorithm'],
    109: [critical, 'When user click on include review radio button,filter should applied'],
    110: [critical, 'When user click on default radio button,filter should applied'],
    111: [critical, 'When user click on as of (yy/mm/dd) radio button,filter should applied'],
    112: [critical, 'When user click on Manage/Edit Topic ,user should see topic update page'],
    113: [critical, 'When user click on View This Version ,user should see agreement page'],
    114: [critical, 'When user click on Object ,user should see Object to this proposed update page'],
    115: [low, 'On Topic Update, All Mandatory Fields are marked with * Sign'],
    116: [low, 'On Topic objection, All Mandatory Fields are marked with * Sign'],
    117: [low, 'On Topic Update, Add New Nick Name link should present for users who doesn\'t have nick name yet'],
    118: [low, 'On Topic Update page, When user doesn\'t put Nick Name , user must see Error Message'],
    119: [moderate, 'When user click on Create New Camp ,user should see Create New Camp page'],
    120: [low, 'On Create New Camp page, All Mandatory Fields are marked with * Sign'],
    121: [low, 'On Create New Camp page, When user doesn\'t put Nick Name , user must see Error Message'],
    122: [low, 'On Create New Camp page, When user doesn\'t put Camp Name , user must see Error Message'],
    123: [moderate, 'When user click on Manage/Edit Camp ,user should see Camp Edit page'],
    124: [low, 'On Camp Update, All Mandatory Fields are marked with * Sign'],
    125: [low, 'On Camp Update page, When user doesn\'t put Nick Name , user must see Error Message'],
    126: [moderate, 'When user click on Manage/Edit Camp Statement ,user should see Statement Update page'],
    127: [low, 'On Statement Update page, All Mandatory Fields are marked with * Sign'],
    128: [low, 'On Statement Update page, When user doesn\'t put Nick Name , user must see Error Message'],
    129: [moderate, 'When user click on Add News ,user should see Add News page'],
    130: [moderate, 'On Add News Page, All mandatory fields are marked with # sign'],
    131: [moderate, 'On Add News page, When user doesn\'t put Display Text , user must see Error Message'],
    132: [moderate, 'On Add News page, When user doesn\'t put Link , user must see Error Message'],
    133: [moderate, 'On Add News Page, When user click on cancel button user should see agreement page'],
    134: [moderate, 'When user click on Edit News ,user should see Edit News page'],
    135: [moderate, 'On Edit News Page, When user click on cancel button user should see agreement page'],
    136: [moderate, 'On Edit News page, When user doesn\'t put Display Text , user must see Error Message'],
    137: [moderate, 'On Edit News page, When user doesn\'t put Link , user must see Error Message'],
    138: [moderate, 'On Edit News page, When user put invalid Link , user must see Error Message'],
    139: [moderate, 'On Add News page, When user put invalid Link , user must see Error Message'],
    140: [moderate, 'On Add News page, When user put valid data , news should get added'],
    141: [moderate, 'On Edit News page, When user put valid data , news should get updated'],
    142: [critical, 'On File Upload page, When user upload file other than jpeg,bmp,png,jpg,gif ,user should see error message'],
    143: [critical, 'On File Upload page, When user upload file more than 5mb size ,user should see error message'],
    144: [critical, 'On File Upload page, When user upload file with same file name ,user should see error message'],
    145: [critical, 'On File Upload page, When user upload file with 0 bytes ,user should see error message'],
    146: [low, 'When user check canonizer.com and click on Google Search button, user should redirect to canonizer.com search page'],
    147: [low, 'When user check web and click on Google Search button, user should redirect to google search page'],
    148: [low, 'When user enters search keyword,check web and click on Google Search button, user should redirect to google search page'],
    149: [low, 'When user enters search keyword,check canonizer.com and click on Google Search button, user should redirect to canonizer.com search page'],
    150: [low, 'On Manage Profile Info Page, When user doesn\'t put Phone Number , user must see Error Message'],
    151: [low,'On Browse Page,When user select /crypto_currency/ethereum/ namespace from drop down, User must see topics under /crypto_currency/ethereum/ namespace'],
    152: [low,'On Browse Page,When user select /crypto_currency/ethereum/ namespace and Only My Topics, User must see own topics under /crypto_currency/ethereum/ namespace'],
    153: [low, 'When user click on Canonizer is the final word on everything with login, page should be loaded Properly'],
    154: [low, 'When user click on Canonizer is the final word on everything without login, page should be loaded Properly'],
    155: [low, 'When user click on Consensus out of controversy use case with login, page should be loaded Properly'],
    156: [low, 'When user click on Consensus out of controversy use case without login, page should be loaded Properly'],
    157: [moderate, 'When user click on Create New Camp link from left menu ,user should see Create New Camp page'],
    158: [moderate, 'On Change Password Page, When user puts invalid new password, user must see Error Message '],
    159: [moderate, 'In Login Page, When user doesn\'t put Email, user must see Error Message'],
    160: [moderate, 'In Login Page, When user doesn\'t put Password, user must see Error Message'],
    161: [low, 'On Login Page, All Mandatory Fields are marked with * Sign'],
    162: [low, 'Login page should have "Forgot Password" link'],
    163: [moderate, 'In Registration page, When user enter duplicate Email, should see error message'],
    164: [moderate, 'In My Supports page, When user click on Topic name, user should redirect to respective page'],
    165: [moderate, 'In My Supports page, When user click on Camp name, user should redirect to respective page'],
    166: [low, 'On Topic Update, When user doesn\'t put Topic Name, user must see Error Message'],
    167: [moderate, 'In Topic Update page, When user enter duplicate Topic name, should see error message'],
    168: [moderate, 'In Create New Camp page, When user enter duplicate Camp name, should see error message'],
    169: [moderate, 'In Camp Update page, When user enter duplicate Camp name, should see error message'],
    170: [moderate, 'On Edit News Page, All mandatory fields are marked with # sign'],
    171: [moderate, 'When user click on Add Camp Statement ,user should see Add Camp Statement page'],
    172: [low, 'On Add Camp Statement page, All Mandatory Fields are marked with * Sign'],
    173: [low, 'On Add Camp Statement page, When user doesn\'t put Nick Name, user must see Error Message'],
    174: [low, 'On Add Camp Statement page, When user doesn\'t put Statement, user must see Error Message'],
    175: [low, 'On Add Camp Statement, Add New Nick Name link should present for users who doesn\'t have nick name yet'],
    176: [moderate, 'In User Registration Page, When user put blank spaces in  First Name, user must see Error Message'],
    177: [moderate, 'In My Supports page, When user click on Topic name->Create New Camp, user should redirect to respective page'],
    178: [moderate, 'In My Supports page, When user click on Camp name->Create New Camp, user should redirect to respective page'],
    179: [moderate, 'In My Supports page, When user click on Camp name->Create New Camp, user should redirect to respective page'],
    180: [moderate, 'With login check disallow: /settings in https://canonizer.com/robots.txt'],
    181: [moderate, 'Without Login check disallow: /settings in https://canonizer.com/robots.txt'],
    182: [low, 'When user goes click on Upload File without logging in, Login Page page should be loaded']
}


